### ISSUE TITLE
Improper timestep labeling on matrix exports

### ISSUE THREAD

**Issue by nickrsan** [Water-Systems-Management-UCM/calvin-network-tools#2]
Via Mustafa:

Once Calvin-network-tools is installed, you should be able to export the whole network as a matrix, which is an input for pyomo version of CALVIN. I have attached two csv files. 'linksWY1922_original.csv' is one*year run (Oct 1921-Sep1922) of the whole network that I have exported a while ago. Today, I exported 'network_linksWY1922.csv' but it does not run because matrix export Java command does not properly label time-step information. CALVIN has monthly time-steps and labeled on node names for the end of day for each month. I am not sure how the Java code creates time-series information but it misses some time-steps and creates incorrect time-steps like 1921-11-29. It should be 1921-11-30 instead. You can compare two csv files to see the difference. The original file includes nodes/links named DBUGSRC and DBUGSNK, which you can ignore as updated CALVIN script can create this debug mode while running the model. After installing all necessary files and software, commandline command to export this one year matrix: 

```
cnf matrix --verbose --format=csv --start=1921-10 --stop=1922-10 --ts=. --fs=, --to=network --outnodes=nodes --max-ub=1000000000
```

**Comment by nickrsan** [comment]
Hi @msdogan,

If I export the entire network for all years, I don't see any items that get a timestep of 11-29 - I used the command you gave me to start, but then expanded it for every year - do you have a resulting file I can see that does that? Are you using the version from GitHub, or a version from npm? I don't know whether these are still synced or not. @mlmaskey have you encountered any incorrect timestep labels and can you provide an example command that produces that error, or point me to a spot where a timestep is dropped from the output? I can go looking for missing timesteps, but it'd be much more efficient if you know where one occurs. Thanks!

**Comment by msdogan** [comment]
Hi @nickrsan, I use npm version `6.13.4` and node version `12.16.0`. When I exported the subnetwork (1 year), for example, I got following links with incorrect time-steps. And there is many more.
`AGS_SD.1921-11-29,SINK.1921-11-29,0,0.00000,1.00000,0.000,1000000000`
I also tried the whole network for all years and got those incorrect time-steps, again. Attached file is network export for one year.
[network_linksWY1922.xlsx](https://github.com/Water-Systems-Management-UCM/calvin-network-tools/files/4970607/network_linksWY1922.xlsx). If it is happening just for me, I can try deleting and installing calvin-network-tools again. Thanks!

**Comment by nickrsan** [comment]
Thanks Mustafa - I'm wondering if it's a data issue, but also need a bit more info. Can you run:
```
npm info calvin-network-tools
```
and share the output with me? That will tell me what your environment and code versions are like too. I'm assuming you're using the latest version of the calvin-network-data repository as well? Can you double check that for me too? Thanks for the file - it helps to see it all in context.

**Comment by mlmaskey** [comment]
Thank you @msdogan, for the file. In fact, I had similar problem and also fewer rows than GitHub has. I do know why but I tried with following command:
`cnf matrix --format csv --start 1921-10 --stop 1922-10 --ts . --to linksWY1922 --max-ub 1000000000000 --debug all --verbose`
Insted of :
`cnf matrix --format csv --start 1921-10 --stop 1922-09 --ts . --to linksWY1922 --max-ub 1000000000000 --debug all --verbose`
It seems weird but is working in my case without getting `11-29`.  I guess it could be the indexing problem as JavaScript starts from 0 not 1.  
I hope this explanation works for @msdogan and @nickrsan .
What do you think, pleas let me know? 
Thanks

**Comment by nickrsan** [comment]
Hi Mustafa and Mahesh,

So, this is a funny issue, and it's a timezone issue - I'm still chasing down *why*, but Mustafa, as a temporary workaround, you shouldn't see this issue if you set your timezone to US/Pacific. There's something about how it reads and processes dates that causes it to mess up the dates for sinks in the eastern hemisphere (🤦). Still looking into this.

**Comment by nickrsan** [comment]
This is for my own notes, but I think you'll appreciate this - it's a comment from Justin in, what I think is an unrelated part of the code. But I bet it's handling the dates similarly, and experiencing the same issue:
```javascript
      // HACK
      // Currently crazy DSS date math as this one day past actual date.
      // Reading into JavaScript reads it as Zulu.  Running script in US
      // it will result in d.getDate() reading in local time, one day earlier...
      // not dealing with JS date crappyness for now.  If you run this in Europe or
      // asia, I appologies.  Feel free to fix.
```

**Comment by nickrsan** [comment]
Hi Mustafa - I was able to resolve this issue - next time you're back in the office, will you try this again (without modifying your computer's time settings - it should work properly from Turkey or anywhere). For documentation, this was related to a function that creates timesteps when there isn't a timeseries file explicitly defined for a node/link. It used a mix of UTC and timezone aware calculations before - moving everything to UTC time calculations resolved the issue (easier said than done though!). 

I'll update the main repository within the ucd-cws organization now so you can update from there. Note that I don't currently have the ability to release a new version on NPM, so please make sure to update via the version on github and let me know how it goes.

**Comment by msdogan** [comment]
Hi Nick,

I would never expect this would be a timezone issue :) I pulled latest version from `ucd-cws/calvin-network-tools` and run the command but it is still creating incorrect timesteps. I guess I am running globally via npm. It's been a while, @nickrsan could you remind me how to run locally from github?

I changed timezone of my computer and run the command and problem was solved as you said. Did not get mislabeled timesteps.

This is what I got when I run `npm info calvin-network-tools`

`(base) C:\Users\PC>npm info calvin-network-tools

calvin-network-tools@3.0.5 | ISC | deps: 20 | versions: 66
Command line tools for calvin-network-data and calvin-network-app. Includes prm tool for export PRI and DSS files
https://github.com/ucd-cws/calvin-network-tools#readme

keywords: water, California, CALVIN, HOBBES, UC Davis, Center for Watershed Sciences, HEC-PRM

bin: cnf

dist
.tarball: https://registry.npmjs.org/calvin-network-tools/-/calvin-network-tools-3.0.5.tgz
.shasum: 1ba041276c6e39c7312cae3ca4e695ac7ea778c9

dependencies:
adm-zip: ^0.4.7                deep-diff: ^0.3.3              sprintf-js: ^1.0.3
async: ^1.4.2                  extend: ^3.0.0                 stream-transform: ^0.1.2
cli-spinner: ^0.2.5            graphviz: 0.0.8                superagent: ^1.4.0
colors: ^1.1.2                 hobbes-network-format: ^2.0.10 walk: ^2.3.9
commander: ^2.9.0              minimist: ^1.2.0               xlsx: ^0.8.0
csv-parse: ^1.0.0              node-uuid: ^1.4.7              yargs: ^6.6.0
csv-stringify: 0.0.8           rimraf: ^2.4.3

maintainers:
- jrmerz <jrmerz@gmail.com>

dist-tags:
latest: 3.0.5

published over a year ago by jrmerz <jrmerz@gmail.com>`

**Comment by nickrsan** [comment]
Hi Mustafa,

So, let's try this - can you run `npm update -g calvin-network-tools` again? And then once that runs, give it another try. Justin gave me access to update the NPM builds of the repository, so the new code is there now. I'll add some documentation on installing from GitHub at some point, but this is fastest, for now, I think.

**Comment by msdogan** [comment]
Hi Nick,

I have updated npm and problem is solved. Thanks a lot!
